### ISSUE TITLE
Compiling Contracts

### ISSUE THREAD

**Issue by mikedeshazer** [ProofSuite/TokenSaleGeneratorCLI#3]
When compiling contracts, you Token.sol inside /src/contracts/solidity/ should probably be .gitignore'd for ability to contribute to the project, without sending over your generated projects to github.

**Comment by Dvisacker** [comment]
Removed solidity files in /src/contracts/solidity/ folder in commit [f3c54f0](https://github.com/ProofSuite/TokenSaleGeneratorCLI/commit/f3c54f091bf22e87f82e10017a4cfdd3b5657a40)
